### ISSUE TITLE
Merging efforts

### ISSUE THREAD

**Issue by AlexisQapa** [cx-org/CombineX#19]
Hi,

Thank you for tackling the combine requirements issue. I believe this will help a lot but will require a lot of contributions. 

There is another port being build at https://github.com/broadwaylamb/OpenCombine.
Maybe you could merge yours efforts ? I'm opening the same issue on the other repo.

**Comment by ddddxxx** [comment]
The difference between CombineX and OpenCombine, FYI.

Diff | CombineX | OpenCombine
---- | --- | ---
First Commit | Jun 9, 2019 | Jun 10, 2019
Progress | Almost 100% | About 30%
Managed by | [Organization](https://github.com/cx-org) | [Individual](https://github.com/broadwaylamb)
Combine Compatibility | Yes (with CXCompatible and CXShim) | No
Side Projects | [CXCocoa](https://github.com/cx-org/CXCocoa) and [CXExtensions](https://github.com/cx-org/CXExtensions) | No
Dependency | Foundation.NSLock | No
Supported Platform | Apple, Linux, Windows | Apple, Linux
Supported Library | Foundation and Dispatch (with CXFoundation) | Dispatch (with OpenCombineDispatch)
API / Behaviour Consistency | Yes | Yes
Description / Reflaction Consistency | [No](https://github.com/cx-org/CombineX/wiki/Combine-Consistency) | Yes

**Comment by ddddxxx** [comment]
Corresponding issue: broadwaylamb/OpenCombine#80

**Comment by AlexisQapa** [comment]
Thanks

**Comment by luoxiu** [comment]
Hi, @AlexisQapa , thanks for your attention! 

You're not the first person to mention opencombine to me. 
In fact, there is always someone reminding me of the existence of opencombine, LOL. 
I want to tell these people, Yes! I knew opencombine existed, and I know it long ago.

Here are some facts I want to share:

Yes, OpenCombine has more stars, although I don't know why. 
But CombineX's first commit(June 9th) was earlier than OpenCombine(June 10th). When I first discovered his project, I also had the same idea, to combine our efforts to accomplish the same goal. I contacted the author of OpenCombine and expressed my willingness to gradually merge my work into his project, even my first commit was earlier. 😂 There are many reasons for revoking this decision: implementation details, code style, even design goal!

Now it seems that my decision is correct! I have completed the implementation of all interfaces and a mature combine-compatibility architecture and even Cocoa extensions more than a month ago. **There doesn't seem to be much stuff that CombineX need to merge from OpenCombine, to be honest.**

Yes, we still need a lot of contributions, if you want, come and join us and improve CombineX together. 😉

**Comment by broadwaylamb** [comment]
If we're doing comparison here, I guess it'd be fair to add that:

- OpenCombine does not depend on Foundation and Dispatch (except for OpenCombineDispatch and OpenCombineFoundation shims that were deliberately moved into separate modules). CombineX uses Foundation's `NSLock` under the hood for locking, AFAICT.
- Just checked: out of 348 tests in the OpenCombine test suite, 162 are failing when run against CombineX and passing when run against Apple's Combine. 1 test results in a crash (so I commented it out). This is 46% fail rate. And those are the tests that compile. There are actually more tests in the OpenCombine test suite, but they don't compile because some publishers in CombineX don't conform to `Equatable`, when they should.
- Out of those 115 CombineX tests that compile against OpenCombine (yep, in OpenCombine fewer operators are implemented, for now), only 15 are failing when run against OpenCombine, resulting in 12% fail rate.

Yep, I could quickly implement the remaining operators with the semantics "somewhat close" to Combine and after that start gradually fixing it, but I chose to polish all the nontrivial corner cases before releasing the code with unexpected behavior, so that it has exactly the same semantics (and performance!) as Combine. Both approaches are perfectly valid, but I personally most enjoy the latter.

But still, great job with implementing the functionality so quickly, @luoxiu!

(Attaching the files so you could reproduce my test results)

- [OpenCombineTestsAgainstCombineX.zip](https://github.com/cx-org/CombineX/files/3728542/OpenCombineTestsAgainstCombineX.zip)
- [CombineXTestsAgainstOpenCombine.zip](https://github.com/cx-org/CombineX/files/3728616/CombineXTestsAgainstOpenCombine.zip)

**Comment by FranzBusch** [comment]
I also think merging efforts makes sense and there should be a way to find a common way of doing implementation and git workflow etc. I think both sides have their advantages and disadvantages. it feels like a wasted effort with two projects aiming to do the same thing. Maybe we can start with a common test suite.

**Comment by luoxiu** [comment]
@broadwaylamb Wow! Thanks!

I will trace these failed tests~ As I said on README, at the moment, the number of tests is far from enough, we do need more tests.

**Comment by luoxiu** [comment]
@broadwaylamb I just deleted a reply because my partner @ddddxxx said it was a bit offensive to read. 

If it's true, sorry for my poor English, 🤣

**Comment by broadwaylamb** [comment]
@luoxiu no worries, I haven't found it offensive at all.

**Comment by luoxiu** [comment]
@FranzBusch 

Thanks for the advice! I am willing to learn OpenCombine's advantages. As for merging, that would be very troublesome...

**Comment by ddddxxx** [comment]
@broadwaylamb Thanks for your clarification (I've updated my comparison between CombineX and OpenCombine). I think we all agree that due to different design choice we made, Merging CombineX and OpenCombine do more harm than good. Though there's still some waste efforts can be avoided. I think we could share test cases.

[CXShim](https://github.com/cx-org/CombineX/wiki/Combine-Compatible-Package) is designed to filling the gap between different Combine implementation. We can build tests on it.
